from django.test import TestCase
from unittest import skip

from lists.models import List, Item
from lists.forms import ItemForm, EMPTY_ITEM_ERROR


class ItemFormTest(TestCase):

    @skip
    def test_form_renders_text_input(self):
        form = ItemForm()
        self.fail(form.as_p())  # this will display autogenerated HTML

    def test_form_save_handles_saving_to_a_list(self):
        list_ = List.objects.create()
        form = ItemForm(data={'text': 'do me'})
        new_item = form.save(for_list=list_)
        self.assertEqual(new_item, Item.objects.first())
        self.assertEqual(new_item.text, 'do me')
        self.assertEqual(new_item.list, list_)

    def test_form_item_input_has_placeholder_and_css_classes(self):
        form = ItemForm()
        self.assertIn('placeholder="Enter a to-do item"', form.as_p())
        self.assertIn('class="form-control form-control-lg"', form.as_p())

    def test_form_validation_for_blank_items(self):
        form = ItemForm(data={'text': ''})
        self.assertFalse(form.is_valid())  # is_valid() populates .errors dict
        self.assertEqual(form.errors['text'], [EMPTY_ITEM_ERROR])  # one field can have more errs
